### ISSUE TITLE
Improving the Spanish differenciator (quick, but important)

### ISSUE THREAD

**Issue by germanvaleroelizondo** [lucaboesch/moodle-local_differentiator#10]
Hi Luca,

While the differentiator now shows the Spanish words, the differences between English and Spanish grammar mean we really need to make some minor, but very important, changes:

The words 'Students will' must be transated as 'los estudiantes serán capaces de' instead of the current 'Los estudiantes harán'.

The word 'one' must be translated as 'uno' instead of the current 'un'.

Otherwise, it works beautifully.

Thanks in advance.

Congratulations!

**Comment by lucaboesch** [comment]
Thanks a lot, Germán!
The 'uno' I've amended in release v1.1.1 as well as 'apreciar'.
For 'los estudiantes serán capaces de' it is all up to the es_mx and es AMOS language maintainer.
The contributions are pending there, waiting for approval.
The complete italian and 'es' strings, too, by the way.
Best,
Luca

**Comment by germanvaleroelizondo** [comment]
Thanks Luca.

I have fixed the AMOS string.

I have been thinking about the English language string for  prethinkingskill | local_differentiator, that you currently have as 'Students will' .

While this string works perfectly in English, it can not be exactly translated in other languages where the future tense for the (following) verb is indicated in the verb itself (in another string), thereby making it impossible to have an accurate translation.

What the French (and now the Mexican Spanish) translations have done in AMOS, for the plugin to make sense grammatically, was to translate this string as if it actually were 'Students will be able to'.

Maybe that would be a grammatically better construction (for translation purposes) than the current string, but I do not know if it changes too much the intended  meaning of the learning goal.

Anyway, the plugin should now work grammatically nice in the Mexican Spanish language pack, as it does in French.

I will now send all the es_mx strings to the international Spanish language pack maintainers in AMOS. They may take quite a while to process the contribution, as they currently have 8 pending contributions from me (one from July).

**Comment by lucaboesch** [comment]
Maybe you could direct message the language maintainers Miguel Rojo Revenga and/or Alberto Rodríguez Orihuela?
That seems like an extremely long waiting time to me.

**Comment by germanvaleroelizondo** [comment]
No need to hurry them now. They seem to be on their winter holidays period.

I am afraid they are extremely careful with the correctness of their Spanish languge, as used in Spain. 

And it takes them a very long time to adjust the peculiar Mexican variation of the Spanish language that I sometimes use (I am a veterinary pathology lecturer) into the proper Spanish language as it should be spoken in Spain.

As the kiwis say "No worries, mate".

They will process the strings... eventually...
