### ISSUE TITLE
Moodle Docs for this plugin

### ISSUE THREAD

**Issue by germanvaleroelizondo** [lucaboesch/moodle-local_differentiator#11]
Hi Luca,

If you don't mind, I would like to make a short Moodle Docs page for this plugin, to be shown when the user clicks on the 'Moodle Docs for this page' link at the bottom of the page while using this plugin.

I will first make the English Docs page and later the Spanish Doc page.

The page is at https://docs.moodle.org/38/en/Differentiator_local_plugin

Please feel free to add/remove/change as you see fit. 

After that, you can add the 'Documentation for this plugin' link to the 'Useful links' tab in the Moodle plugins database page at https://moodle.org/plugins/local_differentiator.

**Comment by lucaboesch** [comment]
That is so kind, Germán.
Thanks a lot! I'm thinking about translating that MoodleDocs page to german, too.
I've been able to add the link in the Moodle plugins database.
Have a very nice christmas!
Luca

**Comment by germanvaleroelizondo** [comment]
I have now fixed the same typo in the Spanish Docs page too.

I hope you also have a very nice Christmas!
Germán

**Comment by germanvaleroelizondo** [comment]
I would like to thank you for adding me as a translator for your plugin in the Contributors tab :)

**Comment by dinism** [comment]
> If you don't mind, I would like to make a short Moodle Docs page for this plugin, to be shown when the user clicks on the 'Moodle Docs for this page' link at the bottom of the page while using this plugin.
> 
> I will first make the English Docs page and later the Spanish Doc page.

### How can i made it in PT-PT?

**Comment by lucaboesch** [comment]
Dear Dinis the English page exists (thanks to Germán Valero) under https://docs.moodle.org/38/en/Differentiator_local_plugin but maybe if you use a older Version (3.7 or 3.6) then the 'Moodle Docs for this page' link does not work… I try to port the page to the 3.6 and 3.7 english MoodleDocs.
https://docs.moodle.org/all/es/Plugin_local_Diferenciador exists, too (spanish).

In regards of Portuguese Docs I don't think any exit!

https://docs.moodle.org/all/pt_br/ do exist though. They work like a Wiki. You create an account then you can create and edit pages.

Best,
Luca

**Comment by dinism** [comment]
I made the https://docs.moodle.org/all/pt_br/Plugin_local_Diferenciador but is PENDING REVIEW
