### ISSUE TITLE
Support for Spanish language

### ISSUE THREAD

**Issue by germanvaleroelizondo** [lucaboesch/moodle-local_differentiator#6]
Congratulations on this great plugin.

I added the Mexican Spanish translation in AMOS. 

But when I try this plugin in Mexican Spanish, the bulk of the differentiator words inside the grid of the differentiator do not show.

Interestingly, they do show for the italian language, even though the Italian language is not supported at https://byrdseed.com/differentiator/index.php?l=it . Same for the German language.

Would it be possible for this great plugin to support international Spanish and Mexican Spanish languages?

I could easily translate all the English words, if I knew just where and how to do it. 
Not being a programmer (I am a veterinary pathology lecturer) , I would naively think that listing all those words as string variables for this plugin would make them all available for translation in AMOS for all Moodle supported languages.

The reason for this suggestion is because of the large number of registered Moodle sites at https://stats.moodle.org/ that use the Spanish languages.

Thanks in advance.

**Comment by lucaboesch** [comment]
Oh, German, that would be lovely!
The reason for this is that the time wasn't enough to put on an admin interface to translate the terms.
But: I can provide you a sheet online (my proposal would be Google Spreadsheet) where you could edit out the lacking translations in español. The reason they're not all in AMOS but are inserted in database entries at installation time is the mere amount of strings as well as the initial aim to make them highly configurable (that feature could still come one time).
So if you were all right with this, I'll gladly create a sheet for you, just tell me your Google Account email address and off you go.

Best,
Luca

**Comment by germanvaleroelizondo** [comment]
Hi Luca,
My email address is gvalero2013@gmail.com

I have never used Google Spreadsheet, but I hope I can work on it.

Thanks,

Germán Valero

**Comment by lucaboesch** [comment]
Germán, you should have gotten an email with a link giving you access to a sheet that looks somewhat like this. I need you to edit in all terms in the columns I've put an arrow in. 

<img width="1391" alt="grafik" src="https://user-images.githubusercontent.com/377279/71344196-2c641280-2562-11ea-86a5-a99ec84601c7.png">

Thanks for your hard work in advance!

Best,
Luca

**Comment by germanvaleroelizondo** [comment]
I think I have made all the translations :)
Please check wether they look reasonable.
They should work equally for both international Spanish and Mexican Spanish.

Yours sincerely,

Germán

**Comment by lucaboesch** [comment]
That is phantastic, Germán.
Please note that in the thinking skills (I know it is hard to do)

Explicar appears twice
Interpretar appears twice

That is something you should amend. Please search for another term so that they appear only once.

**Comment by lucaboesch** [comment]
I see interpretare is twice in italian, too.
I changed the second explicar to elucidar.

**Comment by lucaboesch** [comment]
Spanish texts have been released with v1.1.0.
Thanks, Germán!

**Comment by germanvaleroelizondo** [comment]
I have fixed the duplicates :)

**Comment by lucaboesch** [comment]
Oh, I'll fix that in the next release then. And italian duplicates, too. Apreciar is just fine.

**Comment by germanvaleroelizondo** [comment]
Great!
